name = "dv5d-tasks"
main = "cloudflare/worker.ts"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "TASKS_KV", id = "ed2e1e64702d48c1b27f7920a58f226a" }
]

[build]
command = "npm run build"
pages_build_output_dir = "dist"
