export const PRESET_COLORS = [
  { name: 'White', value: '#ffffff' },
  { name: 'Slate', value: '#94a3b8' },
  { name: 'Gray', value: '#9ca3af' },
  { name: 'Zinc', value: '#a1a1aa' },
  { name: 'Neutral', value: '#a3a3a3' },
  { name: 'Stone', value: '#a8a29e' },
  { name: 'Red', value: '#f87171' },
  { name: 'Orange', value: '#fb923c' },
  { name: 'Amber', value: '#fbbf24' },
  { name: 'Yellow', value: '#facc15' },
  { name: 'Lime', value: '#a3e635' },
  { name: 'Green', value: '#4ade80' },
  { name: 'Emerald', value: '#34d399' },
  { name: 'Teal', value: '#2dd4bf' },
  { name: 'Cyan', value: '#22d3ee' },
  { name: 'Sky', value: '#38bdf8' },
  { name: 'Blue', value: '#60a5fa' },
  { name: 'Indigo', value: '#818cf8' },
  { name: 'Violet', value: '#a78bfa' },
  { name: 'Purple', value: '#c084fc' },
  { name: 'Fuchsia', value: '#e879f9' },
  { name: 'Pink', value: '#f472b6' },
  { name: 'Rose', value: '#fb7185' },
];
